feat: add config to use Salesforce Tooling API
logstash-plugins/logstash-input-salesforce pull request #26
Opened 2021-04-21 19:28 UTC by mkreth

Salesforce provides information relevant for monitoring of a Salesforce application not only via the standard REST APIs but also via the Tooling API. I.e. the SecurityHealthCheck Score which is a measure also shown within Salesforce telling an admin how their org compares to the security baseline recommended by Salesforce. Extracting this SecurityHealthCheck Score and importing it as a metric to Elasticsearch provides the capability to follow the evolution of the score over time and identify trends.
Example of a pipeline leveraging the Tooling API:
```
input {
    salesforce {
        api_version => '51.0'
        ...
        use_tooling_api => true
        sfdc_object_name => 'SecurityHealthCheck'
        sfdc_fields => [ 'Score' ]
    }
}

output {
    stdout {
        codec => rubydebug
    }
}
```

Output:
```
{
         "Score" => "74"
      "@version" => "1",
    "@timestamp" => 2021-04-21T19:25:29.074Z
}
```

2021-04-21 19:32 UTC, mkreth commented
Closes logstash-plugins/logstash-input-salesforce#27

2021-10-20 19:32 UTC, roaksoax requested changes
Hi @mkreth,

Thank you for taking the time to contribute to this plugin.

Generally speaking, I think your changes look good and simple enough. However, I do think there's two things missing:

1. There's no tests (spec). Would it be possible for you to add such tests? This can be done in two ways:
  * easiest is just to check that the Restforce client is created correctly. by stubbing the class to expect a .new with an object that contains the url passed in the setting
  * Alternative is to have a mocked integration test with something like VCR, which will require getting a test account. We may still have access to a test sandbox in our subscription. helpdesk@ should be able to answer that

2. This PR is adding a setting but it's not being documented. Would it be possible for you to please add the appropriate docs in docs/index.asciidoc (This would be the setting itself and description, including a link to the external documentation if at all possible).

Thanks again for taking the time. Let me know if there's anything else I can do to help.

PS. Please note that this is a community driven plugin and we are in the lookout for maintainers. If you are interested in maintaining this plugin long term, we would love your help.

2021-11-04 14:02 UTC, roaksoax approved these changes
Hi @mkreth 

Thank you very much for addressing the requested changes. This looks quite good to me. I'm approving, but will ask @karenzone for a quick review from the docs perspective.

Oh and, similarly to the request in https://github.com/logstash-plugins/logstash-input-salesforce/pull/28#pullrequestreview-795372050, would you please add this change as a note in the changelog (note that both changes can be released under the same version).

2021-11-09 23:28 UTC, karenzone approved these changes
Docs build cleanly and LGTM! Thank you for this contribution and for helping us to improve our docs.

2021-11-11 19:56 UTC, yaauie commented on spec/inputs/salesforce_spec.rb
> +        }
This results in a syntax error:

>  ~~~
> logstash_1_f5d98f22a726 | An error occurred while loading ./spec/inputs/salesforce_spec.rb.
> logstash_1_f5d98f22a726 | Failure/Error: Unable to find org/jruby/RubyKernel.java to read failed line
> logstash_1_f5d98f22a726 | 
> logstash_1_f5d98f22a726 | SyntaxError:
> logstash_1_f5d98f22a726 |   /usr/share/plugins/plugin/spec/inputs/salesforce_spec.rb:217: syntax error, unexpected tSTRING_DEND
> logstash_1_f5d98f22a726 |           }
> logstash_1_f5d98f22a726 |           ^
>  ~~~
> -- https://app.travis-ci.com/github/logstash-plugins/logstash-input-salesforce/jobs/547784881#L487-L493

While Ruby supports either the bracket-block syntax (`{` ... `}`) or the `do` ... `end` syntax, they can't be intermixed.

```suggestion
        end
```

2021-11-11 22:09 UTC, karenzone commented on CHANGELOG.md
> +  - Added `use_tooling_api` configuration to connect to the Salesforce Tooling API instead of the regular Rest API.
Because #28 was published at v3.1.0 before this PR was merged, I believe we'll need to bump the version again--probably to 3.2.0 as this appears to be a feature.

2021-11-11 22:24 UTC, karenzone requested changes
Docs changes are still good. :-) 

I'm thinking that we might have an issue with gem versioning as I mentioned in the changelog.  If this theory does prove out, we'll need to bump the version in the gemspec to match.

2021-11-11 22:24 UTC, karenzone commented on CHANGELOG.md
>    - Switch to restforce v5+ (for logstash 8.x compatibility)
```suggestion
## 3.2.0
  - Added `use_tooling_api` configuration to connect to the Salesforce Tooling API instead of the regular Rest API. [#26](https://github.com/logstash-plugins/logstash-input-salesforce/pull/26)
```

2021-11-11 22:24 UTC, karenzone commented on CHANGELOG.md
>    - Switch to restforce v5+ (for logstash 8.x compatibility)
Because #28 was published at v3.1.0 before this PR was merged, I believe we'll need to bump the version again--probably to 3.2.0 as this PR appears to be a feature. While I am making suggestions, I also suggest add a link to the PR. This info gets picked up in our release notes and is a nice way for users to quickly navigate to the PR if they want to see how the feature was implemented. 

@yaauie, please validate my logic and suggestion here wrt versioning strategy.

2021-11-12 07:13 UTC, mkreth commented on spec/inputs/salesforce_spec.rb
> +        }
Thank you @yaauie! I fixed it.

2021-11-12 07:17 UTC, mkreth commented on CHANGELOG.md
>    - Switch to restforce v5+ (for logstash 8.x compatibility)
Hi @karenzone, thank you for the suggestions. They totally make sense. I've included them and bumped the minor version number again in the gemspec and changelog and also added links to the PRs to both the new and previous entries in the changelog.

2021-11-15 21:20 UTC, karenzone approved these changes
Docs and version bump changes look good to me. Thank you for your contribution, @mkreth. Working with you is a pleasure.

2021-11-15 21:20 UTC, karenzone commented on CHANGELOG.md
>    - Switch to restforce v5+ (for logstash 8.x compatibility)
I see you added the PR link for your previous entry, too.  Bonus points!  :-) Thank you.

2021-11-24 17:19 UTC, mkreth commented
Hello @roaksoax, hello @yaauie,

Is there something I can/should do or could this PR be merged?

Thank you!
Magnus

2021-12-01 06:54 UTC, mkreth commented
> Hello @roaksoax, hello @yaauie,
> 
> Is there something I can/should do or could this PR be merged?
> 
> Thank you! Magnus

Hello @roaksoax, hello @yaauie,
Sorry for chasing you - but did you find time to look into merging this PR?
Thank you,
Magnus

2021-12-07 16:59 UTC, yaauie approved these changes
LGTM 🎉

2021-12-07 16:59 UTC, merged

2021-12-07 17:18 UTC, karenzone commented
Thanks for your contribution, @mkreth! 

Published at v3.2.0: https://rubygems.org/gems/logstash-input-salesforce/versions/3.2.0