Add settings to connect to Salesforce MyDomain url
logstash-plugins/logstash-input-salesforce pull request #28
Opened 2021-06-24 09:17 UTC by mkreth

# Which use case is this pull request trying to solve

We are operating in an environment where we need to explicitly put Salesforce IPs into an allow-list to be able to connect. We are pushed to limit the number of IPs that we are requesting. For us it would hence be helpful to narrow down the number of IPs that we need to connect to. For this we would like more control over which Salesforce endpoint is used by the Salesforce input plugin for authentication and for further API requests. The latter would usually go to the instance url which is returned by the login request. The login request would always go to either login.salesforce.com or test.salesforce.com (depending on the value of the `use_test_sandbox` setting).

# What does this pull request do

This pull request introduces a new configuration setting of the Salesforce input plugin which allows to provide the Salesforce instance url to connect to (already) for authentication and further API requests. The configuration parameter is named `sfdc_instance_url` and takes a string value of the form `<mydomain>.my.salesforce.com`, e.g. the hostname part of the instance url without protocol or path.
If a `sfdc_instance_url` is given, it takes precedence over the `use_test_sandbox` setting and controls the endpoint to which the login request is sent.
If `sfdc_instance_url` is not set, then the `use_test_sandbox` setting will control which endpoint is used.

2021-11-02 09:16 UTC, mkreth reviewed
Requested changes have been incorporated in new version of the pull request.

2021-11-02 14:04 UTC, robbavey requested changes
Code looks great! Thank you for the contribution and your patience. I have a request on the docs, although I will pass over to @karenzone for a final review on documentation.

Would you mind incrementing the version in the `gemspec` file, and adding a note in the changelog explaining the change? As we are adding a new feature to the plugin, we should make this a minor update with the new version `3.1.0`

Thanks again!

2021-11-02 14:04 UTC, robbavey commented on docs/index.asciidoc
> +
Can we please add a note to the effect that either this setting or `use_test_sandbox` can be used, not both

2021-11-02 23:18 UTC, karenzone reviewed
Left some suggestions inline for your consideration.  Let me know what you think.

2021-11-02 23:18 UTC, karenzone commented on docs/index.asciidoc
> +
I agree that this would be helpful to users.  It would be nice to add this info to the `use_test_sandbox` option, too.

2021-11-02 23:18 UTC, karenzone commented on docs/index.asciidoc
> +`login.salesforce.com` or `test.salesforce.com`.
```suggestion
The url of a Salesforce instance. Provide the url if you want to connect to your Salesforce instance instead of
`login.salesforce.com` or `test.salesforce.com` at login.
```

2021-11-02 23:18 UTC, karenzone commented on docs/index.asciidoc
> +`login.salesforce.com` or `test.salesforce.com`.
I added some minor wording tweaks for your consideration. Please see what you think and make sure that I didn't alter your intended message with the suggested rewording.

2021-11-06 09:58 UTC, mkreth commented on docs/index.asciidoc
> +
Thank you for the suggestion - yes, that makes a lot of sense.
I have added a sentence (also below for `use_test_sandbox`).
What do you think?

2021-11-06 10:01 UTC, mkreth commented on docs/index.asciidoc
> +`login.salesforce.com` or `test.salesforce.com`.
Thank you! I feel like each time I get a chance to work with somebody that is more experienced at writing tech documentation is a huge learning opportunity for me. Very much appreciated!

2021-11-09 23:21 UTC, karenzone commented on docs/index.asciidoc
> +
Nicely done. Thank you!  ❤️

2021-11-09 23:23 UTC, karenzone approved these changes
Docs build cleanly and LGTM! Thanks for this contribution, and for your care in improving the documentation.

2021-11-11 15:37 UTC, robbavey approved these changes
LGTM.

Thank you for your contribution and your patience on this!

2021-11-11 15:38 UTC, merged

2021-11-11 16:51 UTC, robbavey commented
This plugin has been released as version `3.1.0`. Thanks again!

2021-11-11 16:57 UTC, mkreth commented
Hi @karenzone, @robbavey,
Thank you for your support in getting this merged! It was a great experience working with you!